const labState={component:'button',variant:'primary'};
const labComponents={
  button:{id:'SG-CMP-001',name:'Button',category:'Actions',desc:'Selectable system action slot.',variants:['default','primary','outline','ghost','destructive'],code:v=>`<button class="sg-button ${v}">Primary Slot</button>`,preview:v=>`<button class="sg-button ${v}">${v==='destructive'?'Delete Slot':'Primary Slot'}</button>`},
  card:{id:'SG-CMP-002',name:'Card',category:'Surfaces',desc:'Save-slot surface with metadata and status.',variants:['default','active'],code:v=>`<article class="sg-card ${v==='active'?'is-active':''}">...</article>`,preview:v=>`<article class="sg-card ${v==='active'?'is-active':''}"><div class="card-top"><span class="sg-meta">SG-CMP-002 / SURFACE</span><span class="sg-badge success">STABLE</span></div><h3>Save Slot Card</h3><p>Metadata-rich surface object.</p><div class="card-bottom"><span class="sg-meta">v1.0.0</span><span class="sg-meta">READY</span></div></article>`},
  input:{id:'SG-CMP-003',name:'Input',category:'Forms',desc:'Recessed system memory field.',variants:['default','focus'],code:()=>`<div class="input-demo">SEARCH MEMORY...</div>`,preview:()=>`<div class="input-demo">SEARCH MEMORY...</div>`},
  badge:{id:'SG-CMP-007',name:'Badge',category:'Feedback',desc:'Tiny metadata/status chip.',variants:['default','success','accent','danger'],code:v=>`<span class="sg-badge ${v}">READY</span>`,preview:v=>`<div style="display:flex;gap:8px;flex-wrap:wrap"><span class="sg-badge ${v}"><span class="sg-dot ${v==='success'?'ok':''}"></span>${v==='danger'?'ERROR':'READY'}</span><span class="sg-badge accent">ACTIVE</span><span class="sg-badge success">SYNCED</span></div>`},
  progress:{id:'SG-CMP-011',name:'Progress',category:'Feedback',desc:'Segmented save/load meter.',variants:['default','loading'],code:()=>`<div class="sg-progress"><span></span></div>`,preview:v=>`<div style="width:100%"><div class="progress-meta"><span class="sg-meta">SYNC STATUS</span><span class="sg-meta">${v==='loading'?'LOADING':'READY'}</span></div><div class="sg-progress ${v==='loading'?'is-loading':''}"><span style="transform:translateX(${v==='loading'?'0':'-35%'})"></span></div></div>`},
  table:{id:'SG-CMP-005',name:'Table',category:'Data',desc:'File registry rows and status badges.',variants:['default'],code:()=>`<table class="sg-table">...</table>`,preview:()=>`<div class="table-shell" style="width:100%"><table class="sg-table"><tbody><tr><td><span class="sg-meta">SG-001</span></td><td>Button</td><td><span class="sg-badge success">STABLE</span></td></tr><tr><td><span class="sg-meta">SG-002</span></td><td>Card</td><td><span class="sg-badge accent">ACTIVE</span></td></tr></tbody></table></div>`},
  alert:{id:'SG-CMP-008',name:'Alert',category:'Feedback',desc:'Controlled system notice panel.',variants:['default','danger'],code:v=>`<div class="mini-card">SYSTEM NOTICE</div>`,preview:v=>`<div class="mini-card ${v==='danger'?'is-active':''}"><div class="card-top"><span class="sg-meta">SYSTEM NOTICE</span><span class="sg-badge ${v==='danger'?'danger':'accent'}">${v==='danger'?'ERROR':'READY'}</span></div><h3>${v==='danger'?'Slot unavailable':'Registry connected'}</h3><p>${v==='danger'?'The selected file could not be loaded.':'Components can be installed from the active theme bank.'}</p></div>`}
};
const blocks=[['SG-BLK-001','Hero Save Panel','Marketing',8],['SG-BLK-002','Pricing Storage Tiers','Commerce',10],['SG-BLK-003','Auth Access Panel','Auth',9],['SG-BLK-004','Dashboard Memory Overview','Application',12],['SG-BLK-005','File Registry Table','Data',7],['SG-BLK-006','Settings Memory Bank','Application',11],['SG-BLK-007','Command Overlay','Overlay',6],['SG-BLK-008','Footer System Strip','Site',5]];
function renderLab(){const root=document.querySelector('#component-lab');if(!root)return;const comp=labComponents[labState.component];if(!comp.variants.includes(labState.variant))labState.variant=comp.variants[0];root.innerHTML=`<div class="lab-list"><p class="sg-meta">COMPONENTS</p>${Object.entries(labComponents).map(([key,c])=>`<button class="lab-option ${key===labState.component?'is-active':''}" data-lab-component="${key}"><span class="sg-meta">${c.id}</span><br>${c.name}</button>`).join('')}</div><div class="lab-preview"><div class="preview-head"><div><p class="sg-meta">${comp.id} / ${comp.category.toUpperCase()} / ACTIVE</p><h2>${comp.name}</h2><p>${comp.desc}</p></div><span class="sg-badge accent">${labState.variant}</span></div><div class="lab-stage"><div class="lab-stage-inner">${comp.preview(labState.variant)}</div></div><div class="lab-meta-row"><span class="sg-meta">VARIANT / ${labState.variant.toUpperCase()}</span><span class="sg-meta">THEME / ACTIVE BANK</span></div></div><div class="lab-controls"><p class="sg-meta">VARIANT CONTROLS</p>${comp.variants.map(v=>`<button class="lab-control ${v===labState.variant?'is-active':''}" data-lab-variant="${v}">${v}</button>`).join('')}</div>`;const code=document.querySelector('#lab-code');if(code)code.textContent=comp.code(labState.variant)}
function renderBlocks(){const root=document.querySelector('#block-grid');if(!root)return;root.innerHTML=blocks.map(b=>`<article class="block-card"><div class="card-top"><span class="sg-meta">${b[0]} / ${b[2].toUpperCase()}</span><span class="sg-badge success">READY</span></div><div class="block-preview"></div><h3>${b[1]}</h3><p>${b[3]} components / responsive</p><div class="template-actions"><button class="sg-button outline small" data-block-preview="${b[0]}">Preview Block</button><button class="sg-button ghost small" data-block-copy="${b[0]}">Copy</button></div></article>`).join('')}
function enhanceTemplateCards(){document.querySelectorAll('.template-card').forEach((card,i)=>{if(card.querySelector('.template-actions'))return;const links=['dashboard.html','ai-workspace.html','marketplace.html','docs-manual.html'];const base=window.MOLDY_TEMPLATE_BASE||'templates/';const holder=document.createElement('div');holder.className='template-actions';holder.innerHTML=`<a class="sg-button primary small" href="${base}${links[i]||'dashboard.html'}">Open Full Page</a>`;card.appendChild(holder)})}
function openBlockPreview(id){const block=blocks.find(b=>b[0]===id);if(!block)return;document.querySelector('#modal-meta').textContent=`${block[0]} / BLOCK / READY`;document.querySelector('#modal-title').textContent=block[1];document.querySelector('.modal-details').innerHTML=`<div class="detail-row"><span class="sg-meta">CATEGORY</span><strong>${block[2]}</strong></div><div class="detail-row"><span class="sg-meta">COMPONENTS</span><strong>${block[3]}</strong></div><p>This block is composed from Saveglass primitives and is designed to be copied into a normal app/page layout.</p>`;document.querySelector('.modal-backdrop').hidden=false;document.body.classList.add('modal-open')}
function closeModalPhase2(){document.body.classList.remove('modal-open')}
function initPhase2(){renderLab();renderBlocks();enhanceTemplateCards();document.addEventListener('click',e=>{const c=e.target.closest('[data-lab-component]');if(c){labState.component=c.dataset.labComponent;renderLab()}const v=e.target.closest('[data-lab-variant]');if(v){labState.variant=v.dataset.labVariant;renderLab()}const bc=e.target.closest('[data-block-preview]');if(bc)openBlockPreview(bc.dataset.blockPreview);const copy=e.target.closest('[data-block-copy]');if(copy&&window.showToast)showToast('BLOCK COPIED','Block markup is ready for the registry.','success');const code=e.target.closest('[data-copy-code]');if(code){navigator.clipboard?.writeText(document.querySelector('#lab-code').textContent);window.showToast&&showToast('CODE COPIED','Component snippet copied.','success')}});document.addEventListener('click',e=>{if(e.target.closest('[data-close-modal]')||e.target.classList.contains('modal-backdrop'))closeModalPhase2()});}
setTimeout(initPhase2,0);
