const root=document.querySelector('#app');
const screen=document.querySelector('#mc-screen-content');
const modes={components:'<div class="mc-device-card"><p class="mc-meta">MC-CMP-001 / ACTION</p><h3>Molded Button</h3><button class="mc-btn primary">Press Me, Coward</button><p>Chunky tactile action with a real pressed state.</p></div>',blocks:'<div class="mc-device-card"><p class="mc-meta">MC-BLK-004 / APPLICATION</p><h3>Wellness Control Board</h3><div class="mc-meter"><span></span></div><p>Habit capsules, LCD readouts, and mode buttons.</p></div>',templates:'<div class="mc-device-card"><p class="mc-meta">MC-TPL-002 / TEMPLATE</p><h3>Family Organizer</h3><div class="mc-lcd">TODAY / 06 TASKS / READY</div><p>Friendly dashboard for routines, notes, and reminders.</p></div>',themes:'<div class="mc-device-card"><p class="mc-meta">MC-THM-001 / MODES</p><h3>Theme Modes</h3><div class="mc-palettes"><span class="mc-swatch" style="background:#ff7aad"></span><span class="mc-swatch" style="background:#70e3bd"></span><span class="mc-swatch" style="background:#78c9ff"></span><span class="mc-swatch" style="background:#ffe36e"></span></div><p>Milky Console, Mint Machine, Bubble Lab, Appliance Mono.</p></div>'};
function setMode(mode){screen.innerHTML=modes[mode];document.querySelectorAll('[data-mc-mode]').forEach(b=>b.classList.toggle('is-active',b.dataset.mcMode===mode));toast('MODE LOADED',mode.toUpperCase().replace('-',' ')+' is now active.');}
function setTheme(theme){root.classList.remove('mc-theme-milky','mc-theme-mint','mc-theme-bubble','mc-theme-mono');if(theme!=='milky')root.classList.add('mc-theme-'+theme);document.querySelectorAll('[data-mc-theme]').forEach(b=>b.classList.toggle('is-active',b.dataset.mcTheme===theme));toast('THEME CLICKED','Machine Candy mode loaded.');}
function toast(title,msg){let t=document.querySelector('.mc-toast');if(!t){t=document.createElement('div');t.className='mc-toast';document.body.appendChild(t)}t.innerHTML='<span class="mc-chip">'+title+'</span><p>'+msg+'</p>';clearTimeout(window.mcToast);window.mcToast=setTimeout(()=>t.remove(),2400)}
document.querySelectorAll('[data-mc-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mcMode)));
document.querySelectorAll('[data-mc-theme]').forEach(b=>b.addEventListener('click',()=>setTheme(b.dataset.mcTheme)));
document.querySelectorAll('[data-mc-toast]').forEach(b=>b.addEventListener('click',()=>toast('COPIED','This static preview action is ready.')));
setMode('components');
